
STATE_IDLE              equ 0
STATE_RUN               equ 1
STATE_JUMP              equ 2
STATE_FALL              equ 3
STATE_BREAK             equ 4
STATE_COUNT             equ 5

DIRECTION_LEFT          equ -1
DIRECTION_RIGHT         equ 1

KEY_RIGHT               equ 262
KEY_LEFT                equ 263
KEY_UP                  equ 265
KEY_C                   equ 67

ANIMATION_STATES_CAP    equ 16
ANIMATION_LOOKUP_CAP    equ 8

PARALLAX_LAYER_CAP      equ 16

MASK_NEG                equ 0x80000000
MASK_ABS                equ 0x7FFFFFFF

